version: '3'
services:
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  mysql:
    image: bitnami/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=micropos
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
