spring:
  application:
    name: pos-products
  batch:
    jdbc:
      initialize-schema: "always"
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "micropos"
  datasource:
    url: "jdbc:mysql://localhost:3306/micropos"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"

server:
  port: 8082

springdoc:
  swagger-ui:
    use-root-path: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
