spring:
  application:
    name: pos-counter

server:
  port: 8083

springdoc:
  swagger-ui:
    use-root-path: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/