spring:
  application:
    name: pos-delivery
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "Delivery"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        createDelivery-in-0:
          destination: newOrders

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
